version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
  beego:
    build:
      context: ./beego
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./beego:/app
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
        - mynetwork
  react:
    container_name: react
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - beego
    networks:
      - mynetwork

networks:
  mynetwork: {}
volumes:
  mysql-data: